<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType><TargetFramework>net48</TargetFramework><UseWindowsForms>true</UseWindowsForms>
    <ApplicationManifest>Installer.manifest</ApplicationManifest><ApplicationIcon>..\BatteryPilot\BatteryPilot.ico</ApplicationIcon>
    <AssemblyName>INSTALL BatteryPilot</AssemblyName><Version>0.1.0</Version><DebugType>none</DebugType><DebugSymbols>false</DebugSymbols>
  </PropertyGroup>
</Project>
